config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :services, only: %i[index show new create] do
    resources :bookings, only: %i[new create edit update destroy]
  end

  get '/profile/:id', to: 'pages#profile', as: 'profile'

  # root "articles#index"
  patch "profile/:id/accept", to: "bookings#accept", as: "accept"
  patch "profile/:id/decline", to: "bookings#decline", as: "decline"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :start_date, presence: true
  validates :end_date, presence: true
  # validates :end_date, greater_than: :start_date
  # validates :start_date, greater_than_or_equal_to: Date.today
  belongs_to :user
  belongs_to :service
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :bookings
  has_many :reviews, through: :bookings
  belongs_to :user

  validates :name, :category, :price, presence: true

  include PgSearch::Model
  pg_search_scope :global_search,
  against: [ :name, :category, :description],
  associated_against: {
    user: [ :first_name, :last_name, :username ]
  },
  using: {
    tsearch: { prefix: true }
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews
  has_many :bookings
  has_many :services

  # Les bookings sur mes services
  has_many :requested_services, through: :services, source: :bookings

  # Les services que j'ai booké
  has_many :rented_services, through: :bookings, source: :service

  validates :username, :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:edit, :update, :destroy, :accept, :decline]

  def new
    @booking = Booking.new
  end

  def create

    @booking = Booking.new(booking_params)

    @booking.user = current_user

    @booking.service = Service.find(params[:service_id])

    if @booking.save
      redirect_to profile_path(current_user)
      flash.alert = "Your reservation has been saved"

    else
      redirect_to service_path(@booking.service), status: :unprocessable_entity
      flash.alert = "Erreur"
    end
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to booking_path(@booking)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  def accept
    @booking.status = "Accepted"
    @booking.save
    flash.alert = "Great! You just accepted an offer."
    redirect_to profile_path(current_user)
  end

  def decline
    @booking.status = "Declined"
    @booking.destroy
    flash.alert = "You just declined an offer and it will be deleted from your list."
    redirect_to profile_path(current_user)
  end

private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :service_id, :user_id, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @services = Service.all.reverse.first(3)
  end

  def profile
    @user = User.find(params[:id])
    @user = current_user

    @requested_services = current_user.requested_services
    @sorted_services =  current_user.requested_services.sort_by { |e| e[:start_date] }
  end
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController

  def index
    @service = Service.all
  end

  def new
    @service = Service.new(service_params)
  end

  def create
    @service = Service.new(service_params)
    if @service.save
      redirect_to service_path(@service)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def service_params
    params.require(:service).permit(:name, :category, :price)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[show]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @services = Service.global_search(params[:query])
    else
      @services = Service.all
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.user = current_user
    if @service.save
      redirect_to service_path(@service)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def service_params
    params.require(:service).permit(:name, :category, :price, :description, :image)
  end

  def set_service
    @service = Service.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<h1>Edit your reservation</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsOneNightStar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
      <div class="wrapper">
        <%= render "shared/flashes" %>
        <%= yield %>
        <p class="notice"><%= notice %></p>
      </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
  <div id="container">
    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.photofunky.net/output/image/b/b/4/e/bb4e5d/photofunky.gif)";>
      <div class="banner-container">
        <h1>Make this night a night to remember!</h1>
        <p>Have a special moment with the celebrity you love</p>
        <a class="banner-button" href="/services">Choose now</a>
      </div>
    </div>
    <div class="container mt-5">
      <div class="cards-home">
        <% @services.each do |service| %>
          <%= link_to service_path(service) do %>
          <div class="card-event-home">

            <% if service.image.nil? %>
            <img src="https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2148&q=80" />
            <% else %>
              <img src="<%= service.image %>" alt="">
            <% end %>

            <div class="card-event-infos-home">
              <h2 class="text-ellipsis"> <%= service.name %></h2>
            </div>
          </div>
          <% end %>
        <%end %>
      </div>
    </div>
  </div>

app/views/pages/profile.html.erb
<div class="container-profile" >
 <h1 class="title">Hello, <%= current_user.first_name %>  👋</h1>

<div class="d-flex">
  <div class="card">
    <h2 class="booking-title">My bookings</h2>
      <% if current_user.bookings.any? %>
        <% current_user.bookings.each do |booking|%>
        <div  class="i-booked">
          <p> <strong class='mini-title'>Service:</strong> <%= booking.service.name %></p>
          <p> <strong class='mini-title'>From:</strong> <%= booking.start_date %></p>
          <p><strong class='mini-title'>To:</strong> <%= booking.end_date %></p>
        </div>
        <% end %>
    <% else %>
      <p>Nothing here</p>
    <% end %>
  </div>
  <div class="card">
    <h2 class="booked-title">Who booked me?</h2>
    <% if @sorted_services.any? %>
        <% @sorted_services.each do |booking|%>
        <div class="profile-booked">
        <div>
          <p><strong class='mini-title'>Service:</strong> <%= booking.service.name %></p>
          <p><strong class='mini-title'>booked by:</strong> <%= booking.user.username %></p>
          <p> <strong class='mini-title'>From:</strong> <%= booking.start_date %></p>
          <p><strong class='mini-title'>To:</strong> <%= booking.end_date %></p>
          </div>
          <div class="status">
          <% if booking.status == "Accepted" %>
          <p class="accepted-offer">You accepted this offer</p>
          <% else %>
          <%= link_to 'Accept', accept_path(booking), class: "btn btn-success mx-2", data: {turbo_method: :patch} %>
          <%= link_to 'Decline', decline_path(booking), class: "btn btn-danger", data: {turbo_method: :patch}%>
          <% end %>
          </div>
          </div>
        <% end %>
    <% else %>
      <p>Nothing yet</p>
    <% end %>
    </div>
  </div>
  <%= image_tag("#{image_path 'bro.png'}", alt: "figma", id: 'profile_background_image') %>
</div>

app/views/services/index.html.erb
<h1 id="main-title">Fancy anything? 🤩</h1>
<div class="container">
  <div class="cards">
      <% @services.each do |service| %>
        <%= link_to service_path(service) do %>
          <div class="card-event">
            <% if service.image.nil? %>
              <img src="https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2148&q=80" />
            <% else %>
              <img src="<%= service.image %>" alt="">
            <% end %>
            <div class="card-event-infos p-3 pt-4">
              <h2><%= service.name %></h2>
              <h3 class="pb-3"><%= number_with_delimiter(service.price, delimiter: ' ') %> €</h3>
                <p class="text-ellipsis--2 p-0"><%= service.description %></p>
            </div>
          </div>
        <% end %>
      <% end %>
  </div>
</div>

app/views/services/new.html.erb
<div class="container mt-5">
  <div class="container-new-service">
    <h1>Add your service! ✨</h1>

    <%= simple_form_for @service do |f| %>
      <%= f.input :name %>
      <%= f.input :category, collection: ['Dinner', 'Sport', 'Concert', 'Time'] %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.submit style: "background-color: rgba(190, 155, 102, 1)", class: "mt-3 golden-btn" %>
    <% end %>
  </div>
  <%= image_tag("#{image_path 'bro.png'}", alt: "figma", id: 'service_background_image') %>
</div>

app/views/services/show.html.erb
<div class="container container-show">
  <div class="event">
    <h1 id="second-title"><%= @service.name %></h1>
    <% if @service.image.nil? %>
      <img src="https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2148&q=80" />
    <% else %>
      <img src="<%= @service.image %>" alt="">
    <% end %>
    <h2> Price: <%= number_with_delimiter(@service.price, delimiter: ' ') %> € </h2>
    <p class="event-description"> <%= @service.description %> </p>
  </div>

  <% unless @service.user == current_user %>
    <div class = "reservation">
    <h2>New reservation</h2>

    <%= simple_form_for [@service, @booking] do |f| %>
      <%= f.input :start_date, as: :date, start_year: Date.today.year + 10,
                                  end_year: Date.today.year,
                                  order: [:day, :month, :year] %>
      <%= f.input :end_date, as: :date, start_year: Date.today.year + 10,
                                  end_year: Date.today.year,
                                  order: [:day, :month, :year] %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>

    </div>
  <% end %>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <div class="footer">
  <div class="footer-copyright">
      <i class="fa-solid fa-copyright"></i>2022 OneNightStar Inc.
  </div>

  <div class="contact">Contact</div>

    <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    </div>

</div>

app/views/shared/_navbar.html.erb
<div class="container-general">

  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <div class="img-container text-start">
        <%= link_to root_path, class: "navbar-brand" do %>
          <span style="color: rgba(190, 155, 102, 1)"><%= image_tag "https://i0.wp.com/soayam.com/wp-content/uploads/2021/02/stars.png?fit=128%2C128&ssl=1" %> OneNightStar</span>
        <% end %>
      </div>

      <%= form_with url: services_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a service"
        %>
        <%= submit_tag "Search", class: "btn mx-3", style: "background-color: rgba(190, 155, 102, 1); filter: drop-shadow(0px 4px 24px #9B9068)" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item active">
            <li class="nav-item">
              <%= link_to new_service_path, class: "nav-link" do %>
              <span style="color: rgba(190, 155, 102, 1)">Add you service</span>
              <% end %>
            </li>
              <%= link_to root_path, class: "nav-link" do %>
              <% end %>
            </li>
            <li class="nav-item dropdown">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/jordangangloff", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Home", root_path, class: "dropdown-item" %>
                <%= link_to "Profile", profile_path(current_user), class: "dropdown-item" %>
                <%= link_to "Log out",  destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
            </li>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "nav-link btn btn-success border border-white"%>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>